backend:
  name: git-gateway
  repo: openScouts/mi-rincon-ayuda
  branch: master
  site_domain: mi-rincon-ayuda

media_folder: "media" # Folder where user uploaded files should go

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: "doc" # Used in routes, e.g., /admin/collections/blog
    label: "Documentacion" # Used in the UI
    folder: "/doc" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
